global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true

route:
  receiver: slack
  group_by: ['alertname', 'instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

  routes:
    - match:
        alertname: "CephNodeInconsistentMTU"
      receiver: slack
      repeat_interval: 24h
    - match:
        alertname: "PrometheusTimeseriesCardinality"
      receiver: slack
      repeat_interval: 24h
    - match:
        alertname: "HostPhysicalComponentTooHot"
      receiver: slack
      repeat_interval: 24h
    - match:
        alertname: "HaproxyServerStatusDown"
      receiver: slack
      repeat_interval: 12h

receivers:
  - name: 'slack'
    slack_configs:
      # Change this to your Slack webhook URL
      - api_url: '<SLACK_HOOK_URL>'
        channel: '#<SLACK_CHANNEL>'
        send_resolved: true
        title: "{{ .CommonLabels.alertname }} ({{ .CommonLabels.severity }})"
        color: "{{ if eq .CommonLabels.severity \"critical\" }}danger{{ else }}warning{{ end }}"
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Labels.alertname }}
          *Instance:* {{ .Labels.instance }}
          *Severity:* {{ .Labels.severity }}
          *Description:* {{ .Annotations.description }}

          *Started At (GMT+3):* {{ (.StartsAt.Add 10800).Format "2006-01-02 15:04:05" }}
          *Resolved At (GMT+3):* {{ if .EndsAt.IsZero }}N/A{{ else }}{{ (.EndsAt.Add 10800).Format "2006-01-02 15:04:05" }}{{ end }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']